---
title: Cold Calculations
subtitle: Conflict characteristics and external support in armed conflicts
date: "Version: `r format(Sys.time(), '%B %d, %Y')`"
author: Celine Giese and Thiago R. Oliveira
output: 
  bookdown::word_document2:
    reference_docx: 'sp_template.docx'
    fig_caption: yes
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
bibliography: 'references.bib'
link-citations: yes
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE) 
library(tidyverse)
library(haven)
library(knitr)
library(flextable)
library(officer)
options(scipen=999)
options(knitr.kable.NA = '')
```

::: {custom-style="Abstract"}
Armed conflicts can have devastating and long-lasting consequences, affecting economic development, social structures, and state stability. Understanding how and why states intervene in armed conflicts, particularly through external support, is particularly relevant, as such interventions raise critical questions about international responsibility and complicity in war crimes. Yet, armed conflict has received relatively little attention within criminology. This study seeks to address that gap by investigating factors associated with the provision of external support to armed conflicts. Drawing on data from the Uppsala Conflict Data Programa, we analyse 472 dyads in 212 conflicts between 1975 and 2017 and provide a quantitative assessment of conflict characteristics associated with different types of external support to armed conflicts. Results suggest a 'cold' approach to the provision of external support, where potential supporters consider the conflict dynamics---such as the intensity, duration, and type of conflict---before providing support. This research contributes to a more comprehensive understanding of the interplay between external interventions and conflict dynamics, offering a starting point for criminological discussions around the liability and responsibility of external supporters.
:::

--------------------------------------

Introduction {-}
====

Despite a reduction in conflicts and deaths, the past decade remains the most violent on record [@DaviesShawn2024Ov1a]. War and armed conflicts (AC) profoundly impact parties involved, with ordinary civilians disproportionately suffering due to fatalities, displacement, and long-term public health crises from destroyed infrastructure [@hoeffler2003measuring]. War-torn countries face reduced growth, higher poverty rates, and weakened institutions, with recovery dependent on robust policy reforms [@hoeffler2003measuring]. High-intensity violence during conflicts lowers economic growth, life expectancy, and educational attainment, with these effects often persisting long-term [@LeThai-Ha2022Easi]. Wars and ACs further generate significant spillover effects, with severity influenced by geographic proximity and economic ties to the conflict zone. Regions with stronger economic ties to the conflict zone experience amplified negative impacts, including disrupted stability and heightened uncertainty [@FangXiangming2020TECo; @LeThai-Ha2022Easi]. While inflation and output remain stable in distant countries, the ripple effects of war challenge interconnected global economies, highlighting the complex dynamics between conflict and economic stability [@federle2024price]. The enduring economic and social costs of war underscore its profoundly criminogenic nature [@hagan2002making].

Today, although conflicts are largely fought by developing nations, they rely heavily on advanced military equipment produced by industrial countries, reinforcing military over social investments [@sivard1996world]. The prevalence and complexity of external support (ES) in AC have grown significantly over the past decades. From 1975 to 2017, 80% of intrastate conflicts involved at least one instance of ES, with state actors being the predominant supporters [@MeierVanessa2023Esia]. Recent years have seen systemic shifts in ES, characterised by the rise of multilateral coalitions and collaborative interventions. Nearly one-third of all support instances now involve such coalitions, emphasising burden-sharing and the legitimacy of support [@MeierVanessa2023Esia]. However, recent developments, such as the United States cutting off significant amounts of its financial and military support for Ukraine, and humanitarian aid to Syria [@CenterGlobalDevelopmentUSAIScuts; @UNUSAID], cast doubt on the future of military alliances and joint defence initiatives like the North Atlantic Treaty Organisation (NATO), as well as the accountability and durability of assistance. With many geopolitical tensions and conflicts ongoing, discussions around AC and ES are crucial to the political environment and international relations, raising questions around the responsibility and accountability of external supporters, especially when military actions turn into war crimes [@hagan2002making]. 

While a timely topic, criminology has given little attention to wars and AC [see, e.g., @hagan2015criminology; @hagan2015iraq; @hagan2006science;  @ruggiero2015achilles; @mcgarry2015introduction], and the role of ES has been particularly neglected. Even in the context of research on ES, the content of interventions remains underexplored, despite its impact on conflict trajectories [see, e.g., @CUNNINGHAMDAVIDE.2016PCWH; @KarlénNiklas2017Tlof; @AydinAysegul2012Noti]. This is an important gap in the literature. Integrating criminology, peace and conflict, and economics, this study examines whether conflict characteristics affect the provision of ES and identifies trends and conditions under which ES is provided. We combine the quantitative approach often used by economic research [e.g., focused on financial and spillover implications of conflicts, see @federle2024price; @FangXiangming2020TECo; @sivard1996world], the focus on prevention, resolution, and transformation of conflicts usually emphasised by peace and conflict studies [e.g., **INSERT REFERENCES**], and a critical criminology approach which highlights the criminogenic nature of wars and genocides [e.g., @RuggieroVincenzo2005CWCa; @alma992976076122201631]. By distinguishing between support types, we also aim to provide a more robust understanding of the role of external supporters and their motives, essential for further discussions around liability and responsibility.

This study addresses three research questions: (1) Are conflict characteristics associated with the provision of ES? (2) Are conflict characteristics associated with the form of support provided? (3) does coalition-based support influence what type of support is provided? To address these research questions, we draw on data from two publicly available Uppsala Conflict Data Program (UCDP) datasets: the Dyadic Dataset (Version 18.1), covering conflict characteristics from 1946 to 2018 [@HarbomLotta2008DDoA; @PetterssonTherése2018Ov1], and the External Support Dataset (Version 18.1), which captures ten forms of ES provided in conflicts from 1975 to 2017 [@MeierVanessa2023Esia]. The high-quality data produced by UCDP is methodically gathered, covers mass violence globally, and includes long-term series that are updated once a year. It is the oldest civil war data collection and allows for comparisons between conflicts and nations. Together, the two datasets provide a robust foundation for quantitatively analysing the relationship between conflict characteristics and ES. The study is structured as follows. First, existing literature on AC and ES is reviewed, highlighting gaps in criminological scholarship. The research design and theoretical framework are then described, followed by the methodology, data, and operationalisation. Following the presentation of the findings, it finishes with the discussion and concluding reflections.

Literature Review {-}
====

The landscape of AC has shifted in recent decades, with a rise in internationalised intrastate conflicts where external states support non-state actors opposing governments [@DaviesShawn2024Ov1a]. This study uses the UCDP's definition of AC, which has become a norm for the methodical definition and analysis of conflicts: "a contested incompatibility that concerns government and/or territory where the use of armed force between two parties, of which at least one is the government of a state, results in at least 25 battle-related deaths in a calendar year" [@Themner2018, p.2]. The primary parties in such conflicts include governments, which control the state capital, and opposition organisations, which are formally organised groups using armed force to influence the outcome of the incompatibility. 

Although developing nations fight most of today's conflicts, they are often fought with weapons from industrialised countries, reflecting 20th-century technological advancements [@sivard1996world]. As geopolitical tensions rise, the role of ES in these conflicts has become a central topic of discussion [@federle2024price]. ES, defined as militarily relevant assistance provided by outside parties to active conflicts, is distinct from peacetime activities like arms trade or security reforms [@MeierVanessa2023Esia; @Meier2022]. This support aims to enhance the recipient’s military capabilities and is provided with the clear intent of facilitating military victory over the opposing side [@CunninghamDavidE.2010BrHe; @GregoryShaun2000TFMI]. It includes materiel, knowledge, or services directly aiding warfare but excludes unintentional support like sanctions that weakens a conflict party but is not intended to support the other side. Additionally, diplomatic efforts, humanitarian aid, and mediation offers do not qualify as ES since they do not directly contribute to the military outcome [@Meier2022]. The external nature of support is determined by whether the provider is not a primary warring party in the conflict, even if present in the same territory.

The interplay between conflict characteristics and ES is complex, with interventions---whether direct military actions or indirect aid---often prolonging hostilities and complicating peace efforts [@SawyerKatherine2015TRoE; @KarlénNiklas2023EtDE; @regan2002third]. Understanding why and how states intervene and the consequences of different types of support is vital to analysing external involvement. This research seeks to explore these themes, examining how conflict characteristics shape external interventions.

## The study of armed conflicts in Criminology {-}

Following the so-called ‘century of peace’ (1815–1914), war has continued across regions, yet social sciences have failed to reflect its prevalence or significance. States, through their 'legitimate monopoly of violence' [@weber1946max], justify violence via bureaucratic rationality, framing war as a noble endeavour to solidify authority and autonomy [@WalklateSandra2019TwS]. Historically, war was driven by imperial capitalist expansion, which fuels conflicts through profit-driven globalisation [@RuggieroVincenzo2023Caw; @KleinJoshR2011Tacc]. Even today, economic imperatives often guide responses to war, reducing it to a developmental obstacle. The global capitalist system blurs lines between legitimate but harmful actions, exacerbating violence [@RuggieroVincenzo2005CWCa]. Critical criminologists therefore view war as a form of state crime legitimised by dominant powers who shape international norms to justify past and future conflicts [@KramerRonaldC.2005WAAS]. Despite millions of legitimate killings in war, criminology has been reluctant to challenge the legitimacy of such violence or address its broader systemic causes [@RuggieroVincenzo2005CWCa]. Wartime atrocities are reframed as patriotic acts, aligning with state narratives through techniques of neutralisation [@SykesGreshamM.1957ToNA; @RuggieroVincenzo2005CWCa]. These dynamics underscore the importance of rethinking state authority, as legality and illegality are often strategically maneuvered in the pursuit of power [@RuggieroVincenzo2005CWCa]. Criminologists, long defining crime not only over illegality but over harm [@hillyardandtombs2007], have a unique opportunity to address its multifaceted impacts and advocate for systemic reforms [@McGarryRoss2016IToW; @RuggieroVincenzo2005CWCa]. Due to its central role to conflicts, examining ES is essential to understanding underlying dynamics of AC. It further raises critical questions about complicity and liability for war crimes, and whether ES escalates violence or fosters peace. 

To examine the dynamics of ES, offering insights into the motives and strategies of external intervention, this study analyses ES through the lens of 'hot' and 'cold' conflicts, a principle first developed by Collins [@collins2008]. According to @collins2008 [in @alma992976076122201631, p.98], whether fighting actually breaks out in violent confrontations between individuals or groups depends on "a series of conditions or turning-points that shape the tension and fear in particular directions, reorganising the emotions as an interactional process involving everyone present: the antagonists, audience, and even ostensibly disengaged bystanders." These turning points operate as triggers for later (but still contingent) behaviours and signal a break with the feelings of the past. Criminological studies on mass violence (MV) have looked at the situational dynamics of such acts, distinguishing between 'hot' and 'cold' acts of MV [@alma992976076122201631], reflecting their underlying emotional dynamics. At the core of 'hot' MV is the notion of ‘forward panic’---a form of violence that emerges when prolonged fear and tension build up, then suddenly discharge in a wave of uncontrolled aggression. This pattern is marked by emotional entrainment: participants get caught in a rhythm of escalating violence that feels unstoppable in the moment [@collins2008]. Emotions such as rage, fear, elation, and a sense of moral detachment combine to create a state of high physiological and social arousal. In contrast, ‘cold’ violence is premeditated, detached, and bureaucratised. It reflects deliberate planning and instrumental logic, often implemented through structures of command or strategy. While it lacks the overt emotional frenzy of forward panics, it is no less violent---merely more strategic, procedural, and distanced from immediate confrontation. These categories are not mutually exclusive: conflicts may shift between ‘hot’ and ‘cold’ phases or contain elements of both. Importantly, @collins2008 theory treats emotional dynamics not as irrational noise but as socially organised processes with identifiable triggers and consequences. Applying this lens to the provision of ES, this study hypothesises that external supporters - distant from the emotional immediacy of the battlefield---act more in line with ‘cold’ violence logics. Support decisions are hypothesised to reflect calculated responses to conflict characteristics such as intensity, duration, type, or geopolitical timing (e.g., post-9/11). By testing whether certain conflict characteristics are correlated with the overall provision and type of ES, the study examines whether ES is best understood as a strategic, interest-driven act rather than an emotionally reactive one.

## External support to armed conflicts {-}

Despite only a slight rise in total conflicts over recent decades, the number of actors providing ES has grown [@MeierVanessa2023Esia]. While troop support has declined, the total number of external interventions continues to grow, reflecting persistent interest in shaping conflict trajectories through both direct and indirect means [@DaviesShawn2024Ov1a; @ChangYang-Ming2022Atoc]. By 2017, 77% of active conflict-dyads featured state support for governments alone, driven in part by the post-9/11 counter terrorism focus, which stigmatised support for non-state actors [@MeierVanessa2023Esia]. Multilateral counter-extremism efforts, often led by UN Security Council members, have reinforced this trend [@MeierVanessa2023Esia]. Research on ES in ACs highlights its significant impact on conflict dynamics and outcomes. The provision of ES shapes the onset [@CUNNINGHAMDAVIDE.2016PCWH; @ReganPatrickM2014Doid], duration [@AydinAysegul2012Noti; @AndersonNoel2019CIPC], outcomes [@SawyerKatherine2015TRoE], and recurrence [@KarlénNiklas2017Tlof] of ACs. Interventions, whether direct (troops) or indirect (weapons, logistics, training), frequently prolong conflicts by altering the cost-benefit calculations of belligerents [@TestermanMatthew2015RtCE; @LacinaBethany2006EtSo] and although external aid can alter power dynamics, it frequently intensifies conflicts, complicates negotiations, and reduces the likelihood of peaceful resolutions [@OlsonLounsberyMarie2016FMIP; @SaidemanStephenM.2002DiIR; @SalehyanIdean2011EESf; @PetrovaMarinaG.2019WMIW]. Although ES can improve the odds of military victory [@Balch-LindsayDylan2008TIat], it often exacerbates humanitarian crises, with rebels exploiting moral hazards to attract further intervention [@RauchhausRobertW.2009PPiH; @KarlénNiklas2017Tlof]. Overall, external actors, including state and non-state supporters, play pivotal roles by shaping conflict processes through diverse forms of assistance, such as military training and direct intervention [@GleditschKristianSkrede2007TDoC; @SalehyanIdean2010TDoW; @645083f0-2904-37de-bfb3-649fda2cd398].

The type and target of ES often align with intervening parties' strategic interests. While training and expertise remain the most frequent forms of support, material aid dominates assistance to rebel groups [@MeierVanessa2023Esia; @BerlinMark2023GamH], suggesting that the type of ES provided differs based on the recipients. Support dynamics further vary by conflict intensity, geographic proximity, and the relative strength of involved parties [@GoldmanOgenS.2016Dftr; @MeulewaeterChloé2021Meat; @OlsonLounsberyMarie2016FMIP; @SalehyanIdean2011EESf]. The Cold War intensified conflicts through superpower support, but its end shifted patterns, reducing insurgencies and prolongation, while rebel groups lost aid, leading many conflicts to peter out or end in settlements [@TestermanMatthew2015RtCE; @RobertsJordan2019TaRR]. While previous studies have established correlations between characteristics of conflicts and conflict parties, and quite a few have done so using data from the UCDP [@MeulewaeterChloé2021Meat; @SalehyanIdean2011EESf; @OlsonLounsberyMarie2016FMIP; @TestermanMatthew2015RtCE; @KarlénNiklas2017Tlof; @LeThai-Ha2022Easi], most analysed the correlation between only one or two conflict characteristics and ES. Most studies further focus on the economic and social cost of conflict [e.g., @federle2024price; @TestermanMatthew2015RtCE; @LeThai-Ha2022Easi; @sivard1996world], or on the effects of ES on conflict dynamics, rather than the provision of ES itself. The introduction of the UCDP ESD [@MeierVanessa2023Esia] offers an extensive descriptive overview of ES dynamics and an opportunity for extensive quantitative analysis of ES, making it easier to research ES dynamics. However, questions as to when, why, and how states are likely to intervene remain to be researched.

Previous research shows that external supporters engage in civil conflicts for diverse and strategic reasons, including geopolitical, economic, and ideological motives, as well as specific foreign policy objectives [@FindleyMichaelG.2006RTIi; @MeierVanessa2023Esia]. Economic interests often drive involvement, with external powers seeking to protect trade benefits or access resources by backing domestic victors [@ReganPatrickM.1998CtIO; @KathmanJacobD.2011CWDa]. In some instances, involvement appears benevolent, such as facilitating peace talks [@BhattaraiPrakash2016Tcic]. However, third-party intervention is rarely altruistic; states often aim to weaken adversaries, prevent conflict spillover, or maintain influence in post-colonial regions [@CunninghamDavidE.2010BrHe; @GregoryShaun2000TFMI]. Strategically, sponsoring militant groups enables states to destabilise rivals or gain leverage without direct conflict. Delegating violence minimises costs while exploiting the instability inflicted on adversaries [@SchultzKennethA.2010TEPi; @BapatNavinA.2012USSo]. However, this approach carries risks, including retaliation, escalation, and the possibility that armed groups will pursue independent agendas [@SchultzKennethA.2010TEPi; @MaozZeev2012RaSS]. Shared ethnic or ideological ties between sponsors and armed groups signal shared goals and reduce the risk that resources will be misused [@BerlinMark2023GamH; @SalehyanIdean2010TDoW]. They are therefore among the strongest predictors of ES [@SalehyanIdean2011EESf; @SozerBrendan2016Dopr], as they further facilitate communication and enhance trust, improving cooperation [@alma992983194640301631; @BaconTricia2018ItEo]. However, relying on such ties can oversimplify sponsorship decisions, especially in contexts with multiple potential recipients or competing priorities [@BerlinMark2023GamH]. Ultimately, prior research suggests that ES is a calculated foreign policy tool used to influence conflict outcomes while advancing sponsors’ strategic goals.

## Limitations of past research {-}

The study of ES in ACs has provided critical insights but is hindered by several limitations. Much research focuses predominantly on support for non-state armed groups, particularly rebel organisations, sidelining other actors and minor armed engagements [@WalterBarbaraF.2004DCBC; @QuinnJ.Michael2007StPD; @SalehyanIdean2011EESf]. A focus on rebel groups introduces methodological challenges and selection bias, limiting generalisability to other armed organisations [@AbrahmsMax2018ECAT; @PhillipsBrianJ.2019TGRa]. This neglect obscures patterns of ES across diverse settings, undermining frameworks linking organisational attributes to state sponsorship. Furthermore, the multi-actor dimension of support is frequently overlooked, despite evidence that sponsors selectively support specific groups within fragmented conflicts [@BerlinMark2023GamH]. Studies often emphasise the initial decision to delegate support [@SalehyanIdean2010TDoW; @alma992983194640301631], neglecting how support dynamics evolve throughout a conflict’s lifecycle and the strategic factors influencing its continuation or cessation [@KarlénNiklas2019TotT; @TokdemirEfe2021RRat]. The content of interventions remains underexplored, despite its impact on conflict trajectories. Differentiating between support types---military training, material aid, or safe havens---can highlight distinct effects on outcomes [@RobertsJordan2019TaRR]. Moreover, qualitative approaches dominate the literature, often at the expense of quantitative or mixed method analyses better suited to capturing temporal and contextual variations in support dynamics [@PetrovaMarinaG.2019WMIW]. This research addresses these limitations by examining the interplay between conflict characteristics and different types of ES from a quantitative criminological angle, aiming to provide a starting point for further criminological discussions around the liability and responsibility of external supporters in ACs. By analysing trends in ES provision both within and between conflict-dyads, it further builds on previous research, offering a more nuanced understanding of the strategic factors influencing ES.

Based on the outlined Literature, Figure \@ref(fig:dag) portrays the underlying assumptions and relationships between conflict characteristics and ES to guide empirical analysis. Directed Acyclic Graphs serve as visual tools to encode theoretical assumptions about causal relationships, and guiding variable selection in statistical models [@pearl2009causality; @cinelli2024crash]. They map out the assumed pathways through which observed and unobserved factors influence the outcome; in this case, the provision and form of ES [@FleischerNL2008Udag]. The dependent variable 'provision of ES' is assumed to be both directly and indirectly influenced by independent conflict characteristics (incompatibility, type of conflict, intensity, region, cumulative duration, point in time of the conflict), as well as the identity of the external supporter, the support recipient and their relationship with one another (i.e., colonial ties, shared cultural/ideological ties, a common enemy) and economic and political factors such as trade connections.


Research Design {-}
====

The study aims to test several hypotheses regarding the relationship between conflict characteristics and ES. These hypotheses are grouped based on the type of relationship they examine, focusing on whether conflict characteristics influence the provision of ES, the form of support provided, and the impact of support coalitions on the type of assistance. These conflict characteristics are considered to be strategical factors influencing the provision of ES. Thereby, this study aims to examine whether external supporters follow a 'cold', rational approach to ES. The hypotheses are as follows:

### Hypothesis Group 1 (HG1): Conflict Characteristics affect whether ES is provided to a conflict party {-}

-   a) Conflict intensity affects whether ES is provided.

-   b)	Territorial incompatibility affects whether ES is provided.

-   c)	The cumulative duration of conflict affects whether ES is provided.

-   d)	The type of conflict affects whether ES is provided.

-   e)	Whether a conflict is taking place before or after 9/11 affects whether ES is provided.

-   f)	Whether a conflict is taking place during or after the Cold War affects whether ES is provided.


### Hypothesis Group 2 (HG 2): Conflict characteristics influence what kind of ES is provided {-}

-   a)	Conflict intensity affects what kind of ES is provided.

-   b)	Territorial incompatibility affects what kind of ES is provided.

-   c)	The cumulative duration of conflict affects what kind of ES is provided.

-   d)	The type of conflict affects what kind of ES is provided.

-   e)	Whether a conflict is taking place before or after 9/11 affects what kind of ES is provided.

-   f)	Whether a conflict is taking place during or after the Cold War affects what kind of ES is provided.


### Hypothesis 3 (H3): Whether support is provided in a coalition or as bilateral support affects what kind of ES is provided {-}

Based on Figure \@ref(fig:dag), hypotheses HG1-a through  HG1-f test whether conflict characteristics directly influence the provision of external support. In hypotheses HG2-a through GH2-f, the same conflict characteristics are hypothesised to influence specific forms of support. H3 tests whether coalition support influences the type of ES.^[It is important to note that Figure \@ref(fig:dag) is simply used for visual aid and not as a strict representation of the model. The relationships between conflict characteristics and ES are not necessarily linear or direct, and the model does not imply causal identification as there could be other unmeasured confounders. Instead, it serves as a framework for understanding the complex interplay between conflict characteristics and ES.] While the model captures the relationships between conflict characteristics and ES, it does not account for all potential confounding factors, such as the identity of the external supporter, the support recipient, and their relationship with one another. These factors are represented in gray, indicating that they are not included in the analysis but may still influence the provision and form of ES. A further limitation is that it does not capture the temporal dynamics of conflicts, which could influence the provision and kind of ES. The model assumes that conflict characteristics have a direct impact on ES, but it does not account for potential feedback loops or interactions between variables. For example, the provision of ES could also influence conflict characteristics, such as conflict intensity, creating a cyclical relationship. Despite these limitations, the model provides a structured framework for testing the hypotheses outlined above.


Methodology {-}
====

## Data and measures {-}

This study draws on two key datasets from the Uppsala Conflict Data Program (UCDP): the UCDP Dyadic dataset (Version 18.1) [@HarbomLotta2008DDoA; @PetterssonTherése2018Ov1] and the UCDP External Support dataset (ESD) (Version 18.1) [@MeierVanessa2023Esia]. The UCDP Dyadic dataset provides data on ACs, focusing on dyads---pairs of primary warring parties---and spans from 1946 to 2018, with the unit of analysis being the dyad-year. The dataset includes 2,935 observations across 25 variables, capturing various conflict characteristics such as the type of conflict, incompatibilities, and combatants. The ESD, covering the period from 1975 to 2017, focuses specifically on ES provided to conflict parties, detailing ten types of support such as military assistance, training, and funding. It offers 2,272 observations of 96 variables, coded from open-source material and subjected to intercoder reliability checks. After merging both data sources,^[The two datasets were merged using the common identifiers 'dyad_id' and 'year'. Prior to merging, the datasets were checked for uniqueness to ensure the absence of duplicate rows. The merging process ensured the removal of duplicates, retaining only the necessary columns for analysis. The underlying unit of analysis remains the dyad-year.] the final dataset includes 2234 observations of 123 variables on 472 dyads in 212 conflicts from 1975-2017. The comprehensive information on both conflict characteristics and characteristics of ES allows the study to address research questions about the relationship between the two and the types of support provided by external actors.

Despite their comprehensive nature, these datasets present several limitations. The availability of data on ES restricts the analysis to 1975–2017, excluding recent geopolitical developments. However, the period includes major historical phases---such as the Cold War, the post-Cold War era, and the aftermath of 9/11---during which ES provision changed significantly [@TestermanMatthew2015RtCE; @MeierVanessa2023Esia]. The large sample enables comparative analysis across time, regions, and conflict types, which would be difficult to replicate through primary data collection. Still, UCDP’s state-based definition of AC includes only incompatibilities over government or territory, potentially overlooking underlying causes. Conflicts with fewer than 25 battle-related deaths per year are excluded, as are cases with uncertainty around key variables like incompatibility, actors, or intensity. Geographic precision is also lacking, as location is defined by the government side in a dyad [@Themner2018] rather than where the conflict occurs. The ESD only records first-degree supporters, while second-degree supporters (e.g., states providing logistical assistance or funding regional coalitions) are omitted [@Meier2022]. Although the dataset distinguishes ten types of support, the categorisation simplifies complex, evolving interactions. Non-state troop support is consistently coded as zero, and support from international organisations, diaspora groups, businesses, or religious institutions is excluded [@Meier2022]. Lastly, the ESD’s minimum threshold for recording assistance may result in underreporting minor interventions, potentially affecting the accuracy of conclusions about ES provision. 

Table \@ref(tab:descriptive) provides descriptive statistics for all variables used in this study.

## Analytic strategy {-}

To address hypotheses HG1-a through H3, we use hybrid, within-between regression models that combine desirable aspects of both fixed effects and random effects econometric models [@mundlak1978pooling; @allison2009fixed]. The within-unit component of the model is equivalent to a fixed effects estimator and models within-group differences---in this case, it reflects factors associated with changes in ES provision within the same conflict; while the between-unit component models average differences between conflict dyads. For each form of support, we fit hybrid logistic regression models testing the hypotheses that conflict characteristics and coalition support are associated with ES provision. The core independent variables included incompatibility, conflict type, intensity, cumulative duration, coalition support, and historical periods such as the post-Cold War and post-9/11 eras. Region was initially included but later excluded due to high multicollinearity with conflict type, which led to convergence issues in several models.

Formally, let $i$ denote the conflict dyad, and let $t$ denote the year at which the conflict dyad is occurring, with $t=1$ referring to the year when the conflict began. $Y_{it}=1$ therefore indicates that conflidct dyad $i$ received external support at year $t$, whereas $Y_{it}=0$ indicates otherwise. For each type of external of support, the multilevel within-between model is then defined by

$$
logit(Y) = \beta_0 + \mathbf{\beta_1 \cdot (X_{it} - \bar{X}_i)} + \mathbf{\beta_2 \cdot Z_i} + \mathbf{\beta_3 \cdot \bar{X}_i} + \mu_i + \epsilon_{it},
$$
where $\mathbf{X_{it}-\bar{X}_i}$ is a row vector of demeaned time-varying predictors (e.g., **LIST TIME-VARYING INDEPENDENT VARIABLES HERE**), $\mathbf{Z_i}$ is a row vector of time-constant predictors (e.g., **LIST TIME-CONSTANT INDEPENDENT VARIABLES HERE**), and $\bar{X}_i$ is a row vector of averaged time-varying predictors, now treated as time-constant predictors. $\mu_i$ is a conflict-level random effect that, with $\beta_0$, creates conflict-specific intercepts, and $\epsilon_{it}$ is a disturbance term. $\mathbf{\beta_1}$ is a row vector of coefficients representing within effects, whereas $\mathbf{\beta_2}$ and $\mathbf{\beta_3}$ are row vectors of coefficients reflecting between effects.

Some types of ES had very skewed distributions, such as overall support provision, troop support, foreign troop presence, and training and expertise. Binomial logistic models failed to converge for those variables. To handle such zero-inflated distributions, we fit an alternative version of Equation 1 above using a Poisson function link for those variables.^[Poisson Pseudo Maximum Likelihood (PPML) models are widely endorsed in the methodological literature for producing consistent estimates under conditions where logistic models with FE often encounter separation or quasi-complete separation issues [@SilvaJ.M.C.Santos2006TLoG]. It is also robust to heteroscedasticity and handles high-dimensional FE efficiently---an important feature for longitudinal dyadic conflict data [@correia2020ppmlhdfe]. Given these advantages, PPML offers a methodologically sound alternative to logistic regression in contexts prone to convergence problems.]

Model fit was assessed throughout using the Bayesian Information Criterion (BIC), Akaike Information Criterion (AIC), with lower values indicating better fit [@Gelman_Hill_2006]. An overall comparison of conflict characteristics’ effects on ES was conducted between and within conflicts, with troop support and weapons models selected for detailed analysis. These were chosen due to the strength of their associations with conflict characteristics. They also enabled exploration of how different conflict characteristics correlate with the provision of direct versus indirect support. However, the use of distinct model types across support forms (due to convergence issues) limits the direct comparability between direct and indirect support provisions.

Logistic regression results were interpreted using odds ratios, reflecting the change in odds of receiving support for a one-unit increase in the predictor. Poisson results were interpreted through incidence rate ratios (IRR), indicating the change in expected count of ES provision for a one-unit increase in the independent variable. While the dependent variables are binary, PPML models treat them as count variables---an accepted compromise to allow valid estimation. Multicollinearity was not expected due to the distinct nature of the conflict characteristics. Nevertheless, variance inflation factors (VIFs) were calculated. Standard regression assumptions were tested across models to ensure validity and reliability. Since most predictors were categorical, the linearity assumption did not apply to them, and due to the logistic nature of the models, homoscedasticity and residual normality were not relevant.

Findings {-}
====

## Overall trends in conflict characteristics {-}

Figure \@ref(fig:fig2) shows overall trends in armed conflicts from 1975 to 2017 and Figure \@ref(fig:fig3) displays their regional distribution. Although the total number of conflicts has decreased and minor ACs make up the majority of ACs, recent years have seen a rise in wars. While most conflicts are fought in Asia and Africa, the number of conflicts fought in the Middle East is growing, with conflicts in Asia and the Americas portraying longer duration. In addition, intrastate conflicts are the most common type of conflict, followed by internationalised intrastate conflicts, whose number has been growing since the early 2000s. While there is fluctuation between the incompatibility types 'territory' and 'government', most conflicts in 2017 were about territory and hardly any about territory and government.

## The provision of external support {-}

Figure \@ref(fig:fig4) displays the trends of different types of ES from 1975 to 2017. The provision of ES has risen, with indirect support being the most common and supporters providing three forms of support on average. The provision of support in a coalition has also increased over time.





References {-}
===